import "dotenv/config";
import express from "express";
import session from "express-session";
import pgSession from "connect-pg-simple";
import pg from "pg";
import crypto from "node:crypto";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname=path.dirname(fileURLToPath(import.meta.url));
const app=express(); const PORT=Number(process.env.PORT||3000);
const pool=process.env.DATABASE_URL?new pg.Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false}):null;
app.set('trust proxy',1); app.use(express.json({limit:'100kb'}));
const Store=pgSession(session);
app.use(session({store:pool?new Store({pool,createTableIfMissing:true}):undefined,secret:process.env.SESSION_SECRET||crypto.randomBytes(32).toString('hex'),resave:false,saveUninitialized:false,cookie:{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',maxAge:7*86400000}}));
async function db(sql,p=[]){if(!pool)throw new Error('DATABASE_URL is required for persistent dashboard data');return pool.query(sql,p)}
async function discord(path,opts={}){const r=await fetch('https://discord.com/api/v10'+path,{...opts,headers:{'User-Agent':'AetherDashboard/2.0','Content-Type':'application/json',...(opts.headers||{})}});const t=await r.text();let d;try{d=JSON.parse(t)}catch{d=t}if(!r.ok){const e=new Error('Discord API '+r.status);e.status=r.status;e.data=d;throw e}return d}
function manageable(g){const p=BigInt(g.permissions||'0');return !!g.owner||!!(p&(1n<<3n))||!!(p&(1n<<5n))}
function auth(req,res,next){if(!req.session.user)return res.status(401).json({error:'Not authenticated'});next()}
async function guildAuth(req,res,next){if(!req.session.user)return res.status(401).json({error:'Not authenticated'});const id=String(req.params.guildId);const g=(req.session.guilds||[]).find(x=>x.id===id);if(!g||!manageable(g))return res.status(403).json({error:'You cannot manage this server.'});req.guild=g;next()}
function oauth(){return 'https://discord.com/oauth2/authorize?'+new URLSearchParams({client_id:process.env.DISCORD_OAUTH_CLIENT_ID||process.env.DISCORD_CLIENT_ID||'',redirect_uri:process.env.DISCORD_OAUTH_REDIRECT_URI||'',response_type:'code',scope:'identify guilds'}).toString()}
async function botGuilds(){if(!process.env.DISCORD_TOKEN)return[];try{return await discord('/users/@me/guilds',{headers:{Authorization:'Bot '+process.env.DISCORD_TOKEN}})}catch{return[]}}
const defaults={volume:80,maxQueue:100,autoplay:false,twentyFourSeven:false,repeat:'off',djRoleId:'',musicChannelId:'',logChannelId:'',embedColor:'#8b5cf6',nowPlayingTitle:'Now Playing',footerText:'Aether Music',language:'en',announceNowPlaying:true,deleteCommands:false,allowExternalLinks:true,sourceYouTube:true,sourceSoundCloud:true,sourceSpotify:true,sourceAppleMusic:true,sourceDeezer:true,sourceBandcamp:true,sourceTwitch:true,sourceVimeo:true,sourceRadio:true,sourceDirectUrl:true,requesterDisplay:true,showQueueButtons:true,allowPlaylists:true,allowSearch:true,defaultSearchSource:'youtube',minDjRole:false,logCommands:true,logPlayer:true,logJoins:true,enableAnalytics:true};
app.get('/auth/discord',(_,res)=>res.redirect(oauth()));
app.get('/auth/discord/callback',async(req,res)=>{try{if(!req.query.code)return res.status(400).send('Missing OAuth code.');const body=new URLSearchParams({client_id:process.env.DISCORD_OAUTH_CLIENT_ID||process.env.DISCORD_CLIENT_ID||'',client_secret:process.env.DISCORD_OAUTH_CLIENT_SECRET||'',grant_type:'authorization_code',code:String(req.query.code),redirect_uri:process.env.DISCORD_OAUTH_REDIRECT_URI||''});const tr=await fetch('https://discord.com/api/v10/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!tr.ok)throw Error('OAuth exchange failed');const tok=await tr.json();const [u,g]=await Promise.all([discord('/users/@me',{headers:{Authorization:'Bearer '+tok.access_token}}),discord('/users/@me/guilds',{headers:{Authorization:'Bearer '+tok.access_token}})]);req.session.user={id:u.id,username:u.global_name||u.username,avatar:u.avatar||null};req.session.guilds=g.filter(manageable);res.redirect('/dashboard.html')}catch(e){console.error(e);res.status(500).send('Discord login failed. Check OAuth variables and redirect URI.')}});
app.post('/auth/logout',(req,res)=>req.session.destroy(()=>res.json({ok:true})));
app.get('/api/me',auth,async(req,res)=>{const bg=await botGuilds(),bs=new Set(bg.map(x=>x.id));res.json({user:req.session.user,guilds:(req.session.guilds||[]).map(g=>({...g,botInstalled:bs.has(g.id)}))})});
app.get('/api/guilds/:guildId/meta',guildAuth,async(req,res)=>{const id=req.guild.id;const bg=await botGuilds();const installed=bg.some(g=>g.id===id);let roles=[],channels=[];if(installed&&process.env.DISCORD_TOKEN){try{[roles,channels]=await Promise.all([discord(`/guilds/${id}/roles`,{headers:{Authorization:`Bot ${process.env.DISCORD_TOKEN}`}}),discord(`/guilds/${id}/channels`,{headers:{Authorization:`Bot ${process.env.DISCORD_TOKEN}`}})])}catch{}}res.json({guild:req.guild,installed,roles:roles.filter(r=>!r.managed),channels:channels.filter(c=>c.type===0||c.type===2)})});
app.get('/api/guilds/:guildId/settings',guildAuth,async(req,res)=>{const r=await db('SELECT config FROM guild_settings WHERE guild_id=$1',[req.guild.id]);res.json({...defaults,...(r.rows[0]?.config||{})})});
app.put('/api/guilds/:guildId/settings',guildAuth,async(req,res)=>{const c={};for(const k of Object.keys(defaults))if(req.body[k]!==undefined)c[k]=req.body[k];await db(`INSERT INTO guild_settings(guild_id,guild_name,config) VALUES($1,$2,$3) ON CONFLICT(guild_id) DO UPDATE SET guild_name=EXCLUDED.guild_name,config=EXCLUDED.config,updated_at=NOW()`,[req.guild.id,req.guild.name,c]);await db('INSERT INTO audit_log(guild_id,user_id,action,payload) VALUES($1,$2,$3,$4)',[req.guild.id,req.session.user.id,'settings.update',c]);res.json({ok:true,settings:{...defaults,...c}})});
app.get('/api/guilds/:guildId/player',guildAuth,async(req,res)=>{const r=await db('SELECT state FROM player_state WHERE guild_id=$1',[req.guild.id]);res.json(r.rows[0]?.state||{connected:false,playing:false,track:null,queue:[],volume:80,repeat:'off'})});
app.post('/api/guilds/:guildId/player/:command',guildAuth,async(req,res)=>{const allowed=['join','play','pause','resume','skip','stop','shuffle','previous','disconnect','volume','repeat','clear'];if(!allowed.includes(req.params.command))return res.status(400).json({error:'Unknown player command'});const payload=req.body||{};await db('INSERT INTO bot_commands(guild_id,command,payload) VALUES($1,$2,$3)',[req.guild.id,req.params.command,payload]);await db('INSERT INTO audit_log(guild_id,user_id,action,payload) VALUES($1,$2,$3,$4)',[req.guild.id,req.session.user.id,'player.'+req.params.command,payload]);res.json({ok:true,queued:true})});
app.get('/api/guilds/:guildId/analytics',guildAuth,async(req,res)=>{const days=Math.min(90,Math.max(1,Number(req.query.days||30)));const r=await db(`SELECT event_type,COUNT(*)::int count FROM analytics_events WHERE guild_id=$1 AND created_at>NOW()-($2||' days')::interval GROUP BY event_type ORDER BY count DESC`,[req.guild.id,String(days)]);res.json({days,events:r.rows})});
app.get('/api/guilds/:guildId/audit',guildAuth,async(req,res)=>{const r=await db('SELECT user_id,action,payload,created_at FROM audit_log WHERE guild_id=$1 ORDER BY id DESC LIMIT 100',[req.guild.id]);res.json(r.rows)});
app.use(express.static(path.join(__dirname,'public')));app.get('/',(_,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
app.listen(PORT,()=>console.log('Aether Dashboard 2.0 listening on '+PORT));
