import http from 'node:http';
import { config } from './config.js';
import { playerManager } from './player/PlayerManager.js';
import { logger } from './logger.js';
import { formatDuration } from './util/format.js';

const html = `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Aether Dashboard</title><style>
*{box-sizing:border-box}body{margin:0;background:#09090b;color:#f4f4f5;font:15px system-ui,-apple-system,sans-serif}main{max-width:900px;margin:auto;padding:28px}.brand{letter-spacing:.28em;color:#a78bfa;font-weight:800}.card{margin-top:20px;padding:22px;border:1px solid #27272a;border-radius:20px;background:#111113;box-shadow:0 10px 35px #0005}.muted{color:#a1a1aa}.title{font-size:25px;font-weight:800;margin:8px 0}.bar{height:8px;background:#27272a;border-radius:9px;overflow:hidden;margin:18px 0}.fill{height:100%;background:#8b5cf6;width:0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(120px,1fr));gap:10px}.stat{padding:12px;background:#18181b;border-radius:12px}.controls{display:flex;flex-wrap:wrap;gap:9px;margin-top:16px}button{border:0;border-radius:11px;padding:11px 15px;background:#27272a;color:white;font-weight:700}button:hover{background:#3f3f46}.danger{background:#7f1d1d}.token{width:100%;padding:12px;border-radius:10px;border:1px solid #3f3f46;background:#09090b;color:white;margin-top:10px}</style></head><body><main><div class="brand">AETHER</div><h1>Music Dashboard</h1><div id="app" class="muted">Loading…</div></main><script>
const token=localStorage.aetherToken||'';let guild='';async function api(path,opt={}){opt.headers={...(opt.headers||{}),'x-aether-token':token};const r=await fetch(path,opt);return r.json()}function esc(s){return String(s??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}async function load(){const d=await api('/api/guilds');guild=d[0]?.id||'';if(!guild){app.innerHTML='<div class="card">No active music players.</div>';return}render(d[0])}function render(p){app.innerHTML='<div class="card"><div class="muted">'+esc(p.name)+'</div><div class="title">'+(p.current?'🎵 '+esc(p.current.title):'🎧 Aether is idle')+'</div><div class="muted">'+esc(p.current?.artist||'Start playback in Discord')+'</div><div class="bar"><div class="fill" style="width:'+Math.min(100,p.progress||0)+'%"></div></div><div class="grid"><div class="stat">🔊 '+p.volume+'%</div><div class="stat">📜 '+p.queue+' queued</div><div class="stat">🔁 '+esc(p.loop)+'</div><div class="stat">♾️ '+(p.stay247?'ON':'OFF')+'</div></div><div class="controls">'+['previous','pause','resume','skip','shuffle','stop'].map(a=>'<button class="'+(a==='stop'?'danger':'')+'" onclick="act(\''+a+'\')">'+a+'</button>').join('')+'</div></div><div class="card"><b>Dashboard token</b><input class="token" id="tok" value="'+esc(token)+'" placeholder="Set DASHBOARD_TOKEN"><button style="margin-top:10px" onclick="localStorage.aetherToken=tok.value;location.reload()">Save token</button></div>'}async function act(action){await api('/api/guild/'+guild+'/action',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action})});load()}load();setInterval(load,5000);</script></body></html>`;
function authorized(req){ return !config.dashboardToken || req.headers['x-aether-token']===config.dashboardToken; }
function json(res,data,status=200){res.writeHead(status,{'content-type':'application/json','access-control-allow-origin':'*'});res.end(JSON.stringify(data));}
export function startDashboardServer(){ const server=http.createServer(async(req,res)=>{ if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':'*','access-control-allow-headers':'content-type,x-aether-token'});return res.end()} if(req.url==='/dashboard'||req.url==='/'){res.writeHead(200,{'content-type':'text/html; charset=utf-8'});return res.end(html)} if(!authorized(req))return json(res,{error:'Unauthorized'},401); if(req.method==='GET'&&req.url==='/api/guilds'){return json(res,[...playerManager.players].map(([id,p])=>({id,name:p.guild.name,current:p.current?{title:p.current.title,artist:p.current.artist}:null,progress:p.current?.durationSec?Math.min(100,p.getPositionSec()/p.current.durationSec*100):0,volume:p.volume,queue:p.tracks.length,loop:p.loop,stay247:p.stay247})))} const m=req.url.match(/^\/api\/guild\/([^/]+)\/action$/); if(req.method==='POST'&&m){let body='';for await(const c of req)body+=c;try{const {action}=JSON.parse(body);const p=playerManager.peek(m[1]);if(!p)return json(res,{error:'Guild player not found'},404);if(!['previous','pause','resume','skip','shuffle','stop'].includes(action))return json(res,{error:'Invalid action'},400);p[action]();await p.refreshControls();return json(res,{ok:true})}catch(e){return json(res,{error:e.message},400)}}res.writeHead(404);res.end('Not found')});server.listen(config.dashboardPort,()=>logger.info(`Aether dashboard listening on port ${config.dashboardPort}`));return server; }
